@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImR5bGFuQGFvbC5jb20iLCJzdWIiOiJkeWxhbkBhb2wuY29tIiwianRpIjoiMWFhYmUzMDAiLCJyb2xlIjpbIlNvZnR3YXJlQ2VudGVyIiwiTWFuYWdlciJdLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJuYmYiOjE3NTM5OTU1MjQsImV4cCI6MTc2MTk0NDMyNCwiaWF0IjoxNzUzOTk1NTI1LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.HI2iZG5Llw5tD6lMNPh3AVUVcmvSrclMtAGJPuJWPK0
Accept: application/json
Content-type: application/json

{
"name": "Docker",
"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImR5bGFuQGFvbC5jb20iLCJzdWIiOiJkeWxhbkBhb2wuY29tIiwianRpIjoiODM1ZjdjYzUiLCJyb2xlIjpbIkFkbWluIiwiQm9zcyJdLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJuYmYiOjE3NTM5OTUzNzIsImV4cCI6MTc2MTk0NDE3MiwiaWF0IjoxNzUzOTk1MzczLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.TKfKNH-gX3SxNupou7S7OaCzHFLb9xy9fOZk9Qt3zTo


###

GET {{SoftwareCenter.Api_HostAddress}}/info


###

POST {{SoftwareCenter.Api_HostAddress}}/vendors/c53f4f43-71cd-45bb-9333-2c7cf9afbfaf/items 
Content-Type: application/json

{
    "name": "Word",
    "description": "Do words and stuff",
    "version": "2025"
}

###

PUT {{SoftwareCenter.Api_HostAddress}}/vendors/c53f4f43-71cd-45bb-9333-2c7cf9afbfaf/point-of-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImR5bGFuQGFvbC5jb20iLCJzdWIiOiJkeWxhbkBhb2wuY29tIiwianRpIjoiMWFhYmUzMDAiLCJyb2xlIjpbIlNvZnR3YXJlQ2VudGVyIiwiTWFuYWdlciJdLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJuYmYiOjE3NTM5OTU1MjQsImV4cCI6MTc2MTk0NDMyNCwiaWF0IjoxNzUzOTk1NTI1LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.HI2iZG5Llw5tD6lMNPh3AVUVcmvSrclMtAGJPuJWPK0
Content-Type: application/json

{
  "name": "new name",
  "phone": "new phone",
  "email": "new email"
}
